"""Update Admin model to use password instead of password_hash

Revision ID: b490ad5c935b
Revises: 0c335ee0b1ad
Create Date: 2024-10-29 16:26:50.182856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b490ad5c935b'
down_revision = '0c335ee0b1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_admin_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_email', type_='unique')

    # ### end Alembic commands ###
